import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Pulsar</title>
      </Head>
      <body className={inter.className}>
        <header className="bg-blue-400 shadow">
          <div className="sm:px-6 lg:px-8 container mx-auto">
            <div className="flex justify-between items-center py-4">
              <div className="flex items-center">
                <a href="/">
                  <img
                    className="h-20 w-auto"
                    src="/pulsar-logo.jpg"
                    alt="Pulsar Logo"
                  />
                </a>
              </div>
              <div className="flex items-center">
                {/* Navigation links */}
                <a
                  href="/registration"
                  className="text-white hover:text-gray-600 px-3 py-2 rounded-md text-sm font-medium"
                >
                  Signup
                </a>
                <a
                  href="/login"
                  className="text-white hover:text-gray-600 px-3 py-2 rounded-md text-sm font-medium"
                >
                  Login
                </a>
              </div>
            </div>
          </div>
        </header>

        <main>{children}</main>
        <footer className="bg-white">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-4">
              <p className="text-sm text-gray-500">
                © {new Date().getFullYear()} Your Company Name. All rights
                reserved.
              </p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
